//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartData
    {
        public string date { get; set; }
        public double High { get; set; }
        public double Low { get; set; }
        public double openValue { get; set; }
        public double closeValue { get; set; }
        public double volume { get; set; }
        public double weightedAverage { get; set; }
    }
}
