//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAData
    {
        public string date { get; set; }
        public Nullable<double> EMA24 { get; set; }
        public Nullable<double> EMA48 { get; set; }
        public Nullable<double> EMA120 { get; set; }
        public Nullable<double> EMA240 { get; set; }
        public Nullable<double> EMA480 { get; set; }
    }
}
