//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClient
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoloDBEntities : DbContext
    {
        public PoloDBEntities()
            : base("name=PoloDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChartData> ChartDatas { get; set; }
        public virtual DbSet<EMAData> EMADatas { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<TAData> TADatas { get; set; }
        public virtual DbSet<VolumeData> VolumeDatas { get; set; }
    }
}
