//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolumeData
    {
        public string TimeStamp { get; set; }
        public double TotalVolumeBTC { get; set; }
        public double VolumeDiff { get; set; }
        public double AvgDiff { get; set; }
    }
}
